server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${psv.docker.host}:5432/psv-zwemmen
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 614087
  jackson:
    serialization.write_dates_as_timestamps: false

liquibase:
  enabled: true
  change-log: classpath:database/changelog-master.xml
  default-schema: public

security:
  token:
    secret: 6a031e6347edf62dbeafaddce3c1a3a297b1f2d1c821f7255cb93bd5c0bca05f55ec062cc4e7d355678020cd578ca8105f9b579f28dc745b5a86d31ec4ad325a

psv:
  docker:
    host: localhost