version: '2.1'
services:
  postgres:
    image: postgres:9.5
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psv-zwemmen
  psv-zwemmen-backend:
      image: afernandez/psv-zwemmen-backend:latest
      depends_on:
        - postgres
      ports:
        - "9000:9000"
      environment:
        DATABASE_HOST: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_PORT: 5432