version: '2.1'
services:
  postgres:
    image: postgres:9.5
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psv-zwemmen